# 购买者条约:
# 作者: Brayn_lzh
# QQ: 390807154
# 保修规则:
#   插件永久修复错误(在合理程度内 非买方误操作 非服务端本身问题)
#   包1年内MC版本更替修复
#   对修改过代码的不保修
#   需要保修时请说明问题 务必附上报错内容
#   若需要添加新功能将进行最低量的收费
# 你可以:
#   1.声明这个插件是私用的
#   2.举报他人服务器剽窃该插件
#   3.利用本插件盈利
#   4.修改本插件代码
# 你不可以:
#   1.声明这个插件是你写的
#   2.不能通过卖本插件盈利
# 有可能在不通知您的情况下对本插件进行修改后卖给他人(一般都会通知 并且将返回部分钱)
# 对应不在本条约里的事项请向我联系
name: FarGem
authors: ['Bryan_lzh']
main: Br.FarGem.Main
depend: [BrAPI]
version: 1.4.1

commands:
  FarGem:
    aliases: [fg]
    description: 主命令
    usage: |
        §c/<command> give [玩家名] [宝石名] [等级] >> 给予玩家一个宝石
                §b宝石名可以是remover 或uninstaller
                      §a用于移除或卸除宝石
        §c/<command> all >> 显示全部的宝石
        §c/<command> reload >> 重载全部配置文件
        §c/<command> craft >> 打开合成菜单